### ISSUE TITLE
Vertaisarvio 1

### ISSUE THREAD

**Issue by iidaw** [Uxusino/custom-cards#1]
Sovellus näyttäisi olevan hyvällä mallilla tällä hetkellä. Toimii muuten hyvin, mutta en saanut luotua omaa pakkaa (yksityistä tai julkista). Pakkaa luodessa kun painaa ”Submit” tulee ”internal server error” ja komentoriville ”KeyError: 'csrf_token’”. Voi johtua jostain omistallakin koneella, mutta en tosiaan saanut luotua yhtään pakkaa. Toimivilta osin ohjelmaa on helppo ja mukava käyttää.

Ohjelman käynnistämisessä paikallisesti oli myös hieman haasteita, voi johtua oman koneen jutuista, mutta ajattelin nekin nyt mainita tässä.

- Psycopg2 asentaminen ei onnistu omalle koneelleni, niin jouduin erikseen asentamaan psycopg2-binary. Voisin suositella sen lisäämistä requirements.txt tai jtn, jos haluaa, että varmasti toimii kaikilla koneilla ilman erillisiä asennuksia.
- Riippuvuuksien asennuksessa oli myös jotain haasteita, jouduin asentamaan kaikki riippuvuuksia itse uudelleen, vaikka olin suorittanut komennon ”pip install -r ./requirements.txt”. 
- Riippuvuuksien asennuksen jälkeen ”flask run” kohdalla tuli ilmoitus ”command not found: flask”, joten asensin flaskin uudelleen.
- Jouduin myös asentamaan sqlalchemy:n erikseen uudelleen, koska sen yhteydessä tuli ”ModuleNotFoundError: No module named 'sqlalchemy’”.

Koodista ja tietokannoista:
- Koodi on mielestäni jaettu hyvin moduuleihin niiden tarkoituksen mukaisesti.
-  Metodit ovat selkeitä.
-  Koodi on mielestäni varsin siistiä.
-  Tietokantataulujen määrä on riittävä kurssin vaatimusten tasolla ja SQL-komentoja on käytetty mielestäni laajasti.

Parannuksina mieleen ei oikein tule muuta, kuin jo aiemmin mainittujen ”ongelmien” korjaus (voi siis kyllä johtua omastakin koneesta, mutta kannattaa tarkistaa asia). Lopuksi myös voi tosiaan käyttää aikaa ulkonäköön, mutta se näyttikin olevan suunnitteilla. :)

Hyvää työtä :)

**Comment by Uxusino** [comment]
Kiitos vertaisarviosta! :) Ensi kerralla yritän viedä sovelluksen Fly.io:on, joten ei enää joudu kärsimään näiden paikallisten asennusten kanssa
