### ISSUE TITLE
(Myöhästynyt) vertaisarvio 2

### ISSUE THREAD

**Issue by 0tso** [Uxusino/custom-cards#2]
Sovelluksen koodi on varsin selkeää ja käyttöliittymä ehdottoman käyttökelpoinen.
Ainoaksi korjausehdotukseksi keksin koodista vain sen, että jos sivustolta yrittää kirjautua ulos kirjautumatta ensin sisään (kirjoittamalla url:n suoraan osoitepalkkiin), johtaa tämä palvelimen sisäiseen virheeseen. Muita ongelmia en suoralta käsin keksi.

**Comment by Uxusino** [comment]
Kiitos! Bugi on nyt korjattu.
